### PR TITLE
Add the simphony-mayavi plugin

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
@nathanfranklin  @SGGgarcia  is this ok to merge?

**Comment by nathanfranklin** [comment]
I have only looked at the code changes and it looks good to me. :+1: 

(To run it etc..I wouldn't be able to do that till a week from now).

**Comment by SGGgarcia** [comment]
I can't run it right now, I will look the code and recomment here the time I test it

**Comment by SGGgarcia** [comment]
:+1:

**Pull request merged**
