### PR TITLE
[WIP] Integrate simphony paraview 0.1.1

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
@kitchoi  is this PR relevant anymore?

**Comment by kitchoi** [comment]
@itziakos  I think I can merge part of this branch to the new framework.  Probably close the PR but keep the branch?

**Comment by kitchoi** [comment]
(Pressed the wrong button, will let you close it)

**Comment by itziakos** [comment]
I would not merge code from this branch to master. I would create a new branch for updating to the latest paraview and cherypick code as necssary. The pr will need to be closed anyway.

**Comment by kitchoi** [comment]
Yep.  Closing.

**Pull request closed without merging**
