### PR TITLE
Prepare release 0.1.0

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
@nathanfranklin and @SGGgarcia, This is the pre-release PR for the simphony-framework 0.1.0.
Please have a look and let me know if you see something strange

**Comment by nathanfranklin** [comment]
Tried it.  Works well.  :+1: 

Two minor things I noticed:
 * Would it be better to use the HTTPS clone URLs instead of `git clone git@github.com: ..` in the `README.rst`? 
 * numpy is also needed.  The VM image for travis has it preinstalled but my testing VM (newly installed Ubuntu 12.04 LTS) didn't have it.  I suspect that we should also open issues (e.g. "add numpy to requirements") on the  other repositories, right?

**Comment by itziakos** [comment]
I will fix the numpy problem, but yes after the release we need to open issues just like we do for every other repo

**Comment by itziakos** [comment]
> Would it be better to use the HTTPS clone URLs instead of git clone git@github.com: .. in the README.rst

I will make the changes

**Pull request merged**
