### PR TITLE
Upgrade common 0.2.2

### PR DESCRIPTION
**Pull request by kitchoi**

### CODE REVIEW

**Comment by kitchoi** [comment]
simphony-aviz currently does not support `simphony-common 0.2.2` but this may be fixed within this week.  So we can wait a bit on that before making a release.

The Travis CI error on the push build is due to the fact that travis was particularly slow last night, so the job ran overtime and was canceled.

**Comment by kitchoi** [comment]
I also asked for a release for `simphony-kratos`. ref https://github.com/simphony/simphony-kratos/issues/23

**Comment by kitchoi** [comment]
@nathanfranklin The integration release is almost ready to go.  However I don't have a numerrin license for testing purposes.  Do you have one and can you try it on your end please?

**Comment by nathanfranklin** [comment]
@kitchoi , I just tested it.  All tests pass.

**Comment by nathanfranklin** [comment]
The line (https://github.com/simphony/simphony-framework/blob/upgrade-common-0.2.2/Makefile#L286) can be changed from:
```(cd src/simphony-openfoam; haas foam_controlwrapper foam_internalwrapper -v)```
to
```haas foam_controlwrapper foam_internalwrapper -v)```

as the simphony-openfoam devevelopers have addresssed https://github.com/simphony/simphony-openfoam/issues/25

**Comment by nathanfranklin** [comment]
Related to that, I suspect that https://github.com/simphony/simphony-framework/blob/upgrade-common-0.2.2/Makefile#L223-L228 and https://github.com/simphony/simphony-framework/blob/upgrade-common-0.2.2/Makefile#L75 could changed so that we don't need to keep `src/simphony-numerrin` after the installation occurs.  **Note that I haven't tested this...**

**Comment by nathanfranklin** [comment]
I think https://github.com/simphony/simphony-numerrin/issues/5  is closed so in theory we no longer have to run the tests in `src/simphony-numerrin`.  However, I tried running 
`haas numerrin_wrapper -v` instead of `cd src/simphony-numerrin; haas numerrin_wrapper -v` (https://github.com/simphony/simphony-framework/blob/upgrade-common-0.2.2/Makefile#L24) but no tests were run.  I don't know what is going on there.

**Comment by kitchoi** [comment]
@nathanfranklin  I changed how simphony-numerrin is installed and tested.  Could you try again please?

**Comment by nathanfranklin** [comment]
@kitchoi ,  i used the framework to install/test simphony-numerrin. :+1:

**Comment by kitchoi** [comment]
@nathanfranklin. @itziakos  is it good to merge and release?

**Comment by nathanfranklin** [comment]
:+1:

**Pull request merged**
