### PR TITLE
Added missing 'Make'

### LINKED ISSUE #46: fixes to Readme
add missing "make": 

sudo make base
sudo apt-openfoam
sudo apt-simphony
sudo apt-lammps
sudo apt-mayavi

### PR DESCRIPTION
**Pull request by nathanfranklin**
This fixes #46 by adding the missing "make" in the "sudo make apt-xxx" commands in the README

### CODE REVIEW

**Comment by nathanfranklin** [comment]
@ahashibon , can you take a quick look.  thanks

**Comment by ahashibon** [comment]
ok thanks!

**Comment by itziakos** [comment]
@ahashibon it looks that this PR is closed without been merged.

**Comment by itziakos** [comment]
:+1:

**Pull request merged**
